export const UPDATE_MENU_BIG = 'UPDATE_MENU_BIG'
export const PADDING_HEADER = 'PADDING_HEADER'
export const PADDING_LEFT_CONTENT = 'PADDING_LEFT_CONTENT'
export const WIDTH_SIDEBAR = 'WIDTH_SIDEBAR'
export const WIDTH_RIGHTBAR = 'WIDTH_RIGHTBAR'
export const TEXT_MENU = 'TEXT_MENU'

// TOOLBAR BUTTON ENABLE
export const TOOLBAR_BUTTON_NEW = 'TOOLBAR_BUTTON_NEW'
export const TOOLBAR_BUTTON_EDIT = 'TOOLBAR_BUTTON_EDIT'
export const TOOLBAR_BUTTON_DELETE = 'TOOLBAR_BUTTON_DELETE'
export const TOOLBAR_BUTTON_SAVE = 'TOOLBAR_BUTTON_SAVE'
export const TOOLBAR_BUTTON_CANCEL = 'TOOLBAR_BUTTON_CANCEL'
export const TOOLBAR_BUTTON_REFRESH = 'TOOLBAR_BUTTON_REFRESH'
export const TOOLBAR_BUTTON_POST = 'TOOLBAR_BUTTON_POST'

// TOOLBAR SEARCH
export const TOOLBAR_SEARCH = 'TOOLBAR_SEARCH'

// toolbar
export const LEVEL = 'LEVEL'
export const TAB = 'TAB'
export const STATUS_FORM = 'STATUS_FORM'