import Vue from 'vue'
import {
    library
} from '@fortawesome/fontawesome-svg-core'
import {
    FontAwesomeIcon
} from '@fortawesome/vue-fontawesome'
import {
    faSignOutAlt,
    faCalendarAlt,
    faCircle,
    faChevronCircleDown,
    faCheckCircle,
    faSortAmountDown,
    faChevronLeft,
    faChevronRight,
    faFileExcel,
    faFilePdf,
    faFileCsv,
    faCoffee,
    faList,
    faUser,
    faPlus,
    faMinus,
    faTrash,
    faSync,
    faColumns,
    faFileExport,
    faSearch,
    faEdit,
    faPrint,
    faTrashAlt,
    faTimes,
    faAngleDoubleRight,
    faSave,
    faPaperclip,
    faInfoCircle,
    faBan,
    faSortDown,
    faCog,
    faCogs,
    faArrowUp,
    faArrowDown,
    faAngleDown,
    faChevronDown,
    faTimesCircle,
    faPlusCircle,
    faMinusCircle,
    faBars,
    faLessThan,
    faGreaterThan,
    faPhoneSquareAlt,
    faHandPaper,
    faUtensils,
    faExclamationTriangle,
    faCoins,
    faExclamationCircle,
    faStopwatch,
    faArrowAltCircleLeft,
    faArrowAltCircleRight,
    faCube,
    faBalanceScale,
    faEnvelope,
    faGlobeAmericas,
    // faWhatsappSquare,
    faCommentAlt,
    faPaperPlane,
    faDotCircle,
    faStar,
    faSlidersH,
    faStickyNote,
    faUserCircle,
    faClipboard,
    faTruck,
    faPlusSquare,
    faWrench,
    faDiceD6,
    faCopyright,
    faClipboardList,
    faFillDrip,
    faArrowAltCircleUp,
    faArrowAltCircleDown,
    faUserTie,
    faUsers,
    faCalculator,
    faFile,
    faClipboardCheck,
    faDollarSign,
    faUndoAlt,
    faBullseye,
    faTicketAlt,
    faMapMarkerAlt,
    faBox,
    faParking,
    faKey,
    faCaretUp,
    faMap,
    faMapMarkedAlt,
    faArrowLeft,
    faArrowRight,
    faAngleDoubleLeft,
    faWallet,
    faGlobe,
    faCameraRetro
} from '@fortawesome/free-solid-svg-icons'



library.add(faTruck)
library.add(faStickyNote)
library.add(faSlidersH)
library.add(faStar)
library.add(faDotCircle)
library.add(faPaperPlane)
library.add(faCommentAlt)
// library.add(faWhatsappSquare)
library.add(faSignOutAlt)
library.add(faCalendarAlt)
library.add(faCircle)
library.add(faChevronCircleDown)
library.add(faCheckCircle)
library.add(faSortAmountDown)
library.add(faChevronLeft)
library.add(faChevronRight)
library.add(faFileExcel)
library.add(faFilePdf)
library.add(faFileCsv)
library.add(faCoffee)
library.add(faList)
library.add(faUser)
library.add(faPlus)
library.add(faMinus)
library.add(faTrash)
library.add(faSync)
library.add(faColumns)
library.add(faFileExport)
library.add(faSearch)
library.add(faEdit)
library.add(faPrint)
library.add(faTrashAlt)
library.add(faTimes)
library.add(faAngleDoubleRight)
library.add(faSave)
library.add(faPaperclip)
library.add(faInfoCircle)
library.add(faBan)
library.add(faSortDown)
library.add(faCog)
library.add(faCogs)
library.add(faArrowUp)
library.add(faArrowDown)
library.add(faAngleDown)
library.add(faChevronDown)
library.add(faTimesCircle)
library.add(faPlusCircle)
library.add(faMinusCircle)
library.add(faBars)
library.add(faLessThan)
library.add(faGreaterThan)
library.add(faPhoneSquareAlt)
library.add(faHandPaper)
library.add(faUtensils)
library.add(faExclamationTriangle)
library.add(faCoins)
library.add(faExclamationCircle)
library.add(faStopwatch)
library.add(faArrowAltCircleLeft)
library.add(faArrowAltCircleRight)
library.add(faCube)
library.add(faBalanceScale)
library.add(faEnvelope)
library.add(faGlobeAmericas)
library.add(faMap)
library.add(faMapMarkerAlt)
library.add(faMapMarkedAlt)
library.add(faSlidersH)
library.add(faStickyNote)
library.add(faUserCircle)
library.add(faClipboard)
library.add(faTruck)
library.add(faPlusSquare)
library.add(faCog)
library.add(faWrench)
library.add(faDiceD6)
library.add(faCopyright)
library.add(faClipboardList)
library.add(faFillDrip)
library.add(faArrowAltCircleUp)
library.add(faArrowAltCircleDown)
library.add(faUserTie)
library.add(faUsers)
library.add(faCalculator)
library.add(faFile)
library.add(faClipboardCheck)
library.add(faDollarSign)
library.add(faUndoAlt)
library.add(faBullseye)
library.add(faTicketAlt)
library.add(faBox)
library.add(faParking)
library.add(faKey)
library.add(faCaretUp)
library.add(faArrowLeft)
library.add(faArrowRight)
library.add(faAngleDoubleRight)
library.add(faAngleDoubleLeft)
library.add(faWallet)
library.add(faGlobe)
library.add(faCameraRetro)

Vue.component('font-awesome-icon', FontAwesomeIcon)